name: Update Version

on:
  workflow_dispatch:


jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set fixed version in .csproj
        run: |
          sed -i "s|<Version>.*</Version>|<Version>1.0.0</Version>|g" API.csproj

      - name: Commit version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add API.csproj
          git commit -m "Set version to 1.0.0"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
