name: Version and Tag

on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.x'  # Verwenden Sie Ihre spezifische Version

      - name: Update version in .csproj
        run: |
          tag=$(git describe --tags --abbrev=0)
          versionNumber=${tag#v}
          sed -i "s|<Version>.*</Version>|<Version>$versionNumber</Version>|g" API.csproj

      - name: Commit version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add YourProjectName.csproj
          git commit -m "Update version to $versionNumber"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
