name: Build after push

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build solution
        run: dotnet build --configuration Release
  
  tests:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run tests
        run: dotnet test ./tests/Tests.csproj --configuration Release --no-build
  
