name: Build after push

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    
jobs:    
  tests:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read
    
    steps:
      - name: Run tests
        run: dotnet test Tests/Tests.csproj --configuration Release
  
